#!/usr/bin/env python2.7

import argparse
import subprocess as sp
import os

IMAGE_NAME = "docker_test"

def create_directory(directory):
    # Check existance before creating the directory
    if (os.path.isdir(directory)): return
    print("Creating directory: " + directory)
    os.makedirs(directory)
    sp.call("sudo chown {0}:{0} {1}".format(os.getlogin(), directory))

def run_dev_environment(command, ws_mount):
    docker_args = []
    docker_user = "test"
    dockerfile  = 'docker_test'

    host_user = os.getlogin()
    uid = os.getuid()

    temp_volume = "/home/{}/.{}".format(host_user, IMAGE_NAME)

    # Workspace name
    ws_name = "catkin_ws"

    docker_args.append("-it")
    docker_args.append("--rm")
    docker_args.append("--env=DISPLAY")
    docker_args.append("--env=\"QT_X11_NO_MITSHM=1\"")
    docker_args.append("--volume=/tmp/.X11-unix:/tmp/.X11-unix:rw")
    docker_args.append("--volume=$HOME/.Xauthority:/root/.Xauthority:rw")
    docker_args.append("--name=\"{}\"".format(IMAGE_NAME))
    docker_args.append("--privileged")
    docker_args.append("--network=host")
    docker_args.append("--cap-add=IPC_LOCK")
    docker_args.append("--cap-add=sys_nice")
    docker_args.append("--user {0}:{0}".format(uid))
    docker_args.append("--device /dev/snd")
    # VSCode needs HOME to be defined in order to work in the container
    docker_args.append("-e HOME=/home/{}".format(docker_user))
    # Keep user settings
    docker_args.append("--volume {}/user/:/home/{}/".format(temp_volume, docker_user))
    # Mount workspace
    docker_args.append("--volume {}:/{}".format(ws_mount, ws_name))
    # Use NVIDIA
    docker_args.append("--gpus=all")
    # Sound for Webots
    docker_args.append("--device /dev/snd")
    docker_args.append("--group-add audio")
    # Add sudo group
    docker_args.append("--group-add sudo")

    docker_args.append("-e ROS_HOSTNAME=localhost")
    docker_args.append("-e ROS_MASTER_URI=http://localhost:11311")
    docker_args.append("--workdir /{}/".format(ws_name))

    # Join arguments together separated by a space
    docker_args = ' '.join(docker_args)
    docker_command = "docker run {} {} {}".format(docker_args, dockerfile, command)

    # Give permissions to host directories
    create_directory(temp_volume + "/user/")

    sp.call("xhost +local:docker", shell=True)
    sp.call(docker_command, shell=True)
    sp.call("xhost -local:docker", shell=True)

def attach_dev_environment(command):
    command = 'docker exec -it --user {0}:{0} {1} {2}'.format(os.getuid(), IMAGE_NAME, command)
    sp.call(command, shell=True)

def is_running():
    command = 'docker ps | grep {} > /dev/null'.format(IMAGE_NAME)
    try:
        sp.check_call(command, shell=True)
    except Exception:
        return False

    return True

def main():
    # Parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--cmd', dest='command', default='bash')
    root = sp.check_output('git rev-parse --show-toplevel'.split()).strip().decode()
    parser.add_argument('-ws', '--workspace', dest='workspace', default=os.path.join(root, "catkin_ws"))

    args = parser.parse_args()

    if not is_running():
        run_dev_environment(args.command, ws_mount=args.workspace)
    else:
        attach_dev_environment(args.command)

if __name__ == '__main__':
    main()
